### ISSUE TITLE
数据库文件不全  项目功能不能全部运行

### ISSUE THREAD

**Issue by jykSS** [Azure99/RainngCourse#1]
数据库文件不全  项目功能不能全部运行 缺少'rainng_course.rc_course'

**Comment by Azure99** [comment]
请先创建名为rainng_course的数据库(使用其他名字到后端配置文件中修改)，编码为utf8mb4，然后再执行dump文件。
您也可以直接执行以下三条语句完成导入，另外还需要安装redis和mongodb
CREATE DATABASE rainng_course CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci;
USE rainng_course;
SOURCE rainng_course.sql;

**Comment by jykSS** [comment]
你好 mongodb上面记录的日志如下
### Error querying database.  Cause: java.sql.SQLSyntaxErrorException: Table 'rainng_course.rc_course' doesn't exist
### The error may exist in com/rainng/coursesystem/dao/mapper/CourseMapper.java (best guess)
### The error may involve defaultParameterMap
### The error occurred while setting parameters
### SQL: SELECT   course_id AS id,course_name AS name   FROM rc_course
### Cause: java.sql.SQLSyntaxErrorException: Table 'rainng_course.rc_course' doesn't exist
; bad SQL grammar []; nested exception is java.sql.SQLSyntaxErrorException: Table 'rainng_course.rc_course' doesn't exist

我猜测是不是您上传的那个sql文件少一个rc_course这个 表

**Comment by jykSS** [comment]
多谢 项目已经运行成功了 应该是我的数据库是5.5您的sql导出时用的是比5.5高的版本 有些不兼容,改了下datetime和用户名的大小就好了  
还有一个问题是能提交下admin 教师 还有用户的几个账号密码吗  我看都是加密后的 不知道密码无法登录

**Comment by Azure99** [comment]
密码默认是123456，加密逻辑在service包下的UserService，盐值为_Rain_Ng-_Azure_99
